# This file is auto-generated by the local-whisper release workflow. DO NOT EDIT.
cask "local-whisper" do
  version "0.1.2"
  sha256 "a216aa855b40292d17e1194e67c7a42f67498dad2f8f92e81357dcd2bd749550"

  url "https://github.com/aarondpn/local-whisper/releases/download/v#{version}/LocalWhisper-#{version}.dmg"
  name "LocalWhisper"
  desc "Menu-bar speech-to-text powered by Whisper"
  homepage "https://github.com/aarondpn/local-whisper"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates false
  depends_on macos: ">= :sequoia"

  app "LocalWhisper.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/LocalWhisper.app"]
  end

  uninstall quit: "com.aarondpn.local-whisper"

  zap trash: [
    "~/Library/Application Support/LocalWhisper",
    "~/Library/Caches/com.aarondpn.local-whisper",
    "~/Library/Preferences/com.aarondpn.local-whisper.plist",
    "~/Library/Saved Application State/com.aarondpn.local-whisper.savedState",
  ]
end
