# This file is auto-generated by the local-whisper release workflow. DO NOT EDIT.
cask "local-whisper" do
  version "0.2.0"
  sha256 "6bd236abeb590d0cf1db8a346ce1bff48c73326556a64da4ffb3b545190cfd05"

  url "https://github.com/aarondpn/local-whisper/releases/download/v#{version}/LocalWhisper-#{version}.dmg"
  name "LocalWhisper"
  desc "Menu-bar speech-to-text with on-device Whisper and Nemotron models"
  homepage "https://github.com/aarondpn/local-whisper"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates false
  depends_on macos: :sequoia

  app "LocalWhisper.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/LocalWhisper.app"]
  end

  uninstall quit: "com.aarondpn.local-whisper"

  zap trash: [
    "~/Library/Application Support/LocalWhisper",
    "~/Library/Caches/com.aarondpn.local-whisper",
    "~/Library/Preferences/com.aarondpn.local-whisper.plist",
    "~/Library/Saved Application State/com.aarondpn.local-whisper.savedState",
  ]
end
