# This file is auto-generated by the local-whisper release workflow. DO NOT EDIT.
cask "local-whisper" do
  version "0.1.1"
  sha256 "e2fea17a0414a92134c14b09766747eb5d912a8763d69bde617cd81b689263bc"

  url "https://github.com/aarondpn/local-whisper/releases/download/v#{version}/LocalWhisper-#{version}.dmg"
  name "LocalWhisper"
  desc "Menu-bar speech-to-text powered by Whisper"
  homepage "https://github.com/aarondpn/local-whisper"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates false
  depends_on macos: ">= :sequoia"

  app "LocalWhisper.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/LocalWhisper.app"]
  end

  uninstall quit: "com.aarondpn.local-whisper"

  zap trash: [
    "~/Library/Application Support/LocalWhisper",
    "~/Library/Caches/com.aarondpn.local-whisper",
    "~/Library/Preferences/com.aarondpn.local-whisper.plist",
    "~/Library/Saved Application State/com.aarondpn.local-whisper.savedState",
  ]
end
