# This file was generated by GoReleaser. DO NOT EDIT.
cask "redmine" do
  version "2.9.0"

  on_macos do
    on_intel do
      sha256 "cba69b4b3d56f60dfeb90a2d31dcbf553133ec283f882e2fc6e17b0cc15edd04"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "cdf7b50eda2ff7e405f6600e40640f3c2147034644a1057512b94596ecb0291f"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "498b51fc28a55dc2fffe8f2af70e67f15991eb3e3ae4b50b34dcb35710562f51"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "52da770356e359bd2ddda0ff9f65d8408c54bc69594a6d8d367fa1db2bceb39b"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-arm64.tar.gz"
    end
  end

  name "redmine"
  desc "CLI tool for interacting with Redmine project management"
  homepage "https://github.com/aarondpn/redmine-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redmine"
  bash_completion "completions/redmine.bash"
  fish_completion "completions/redmine.fish"
  zsh_completion "completions/redmine.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redmine"]
  end

  # No zap stanza required

end
