# This file was generated by GoReleaser. DO NOT EDIT.
cask "redmine" do
  name "redmine"
  desc "CLI tool for interacting with Redmine project management"
  homepage "https://github.com/aarondpn/redmine-cli"
  version "1.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redmine"
  bash_completion "completions/redmine.bash"
  zsh_completion "completions/redmine.zsh"
  fish_completion "completions/redmine.fish"

  on_macos do
    on_intel do
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-amd64.tar.gz"
      sha256 "5c2814ad6b05655e54e89979527822eecc7c49f43101e67004448122aa28fcd2"
    end
    on_arm do
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-arm64.tar.gz"
      sha256 "4ddfe567ada2ec39efc7fc3915d939ba81cc4b207d1ed8f5879bb8342b34b988"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-amd64.tar.gz"
      sha256 "7468025b607b0779cbdaa196bdb02397fa6b63cb59d56e5a3bbaed3d28c0e837"
    end
    on_arm do
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-arm64.tar.gz"
      sha256 "ff31d40cb3325e657f3540c07f7ae64462dbba3aac3537d5e2af6238efdf584b"
    end
  end

  # No zap stanza required
end
