# This file was generated by GoReleaser. DO NOT EDIT.
cask "redmine" do
  version "2.11.1"

  on_macos do
    on_intel do
      sha256 "4ef3401bafa4028b9a1a2fb949523a2cad55036afee556309ef278adaaac816e"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5da335bc837175d0fcbe878039c4e00dec0e8110a1baf394128ec7ff8a421821"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "438c7ecc9fddd26ab216721bdfdbcac9c6ebc50dd29f95924a15714a6971a7be"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "65cf3083181f382ec7c0000843d6ea3de34a4c224db736dcd809d016f7ffbba4"
      url "https://github.com/aarondpn/redmine-cli/releases/download/v#{version}/redmine-cli-linux-arm64.tar.gz"
    end
  end

  name "redmine"
  desc "CLI tool for interacting with Redmine project management"
  homepage "https://github.com/aarondpn/redmine-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redmine"
  bash_completion "completions/redmine.bash"
  fish_completion "completions/redmine.fish"
  zsh_completion "completions/redmine.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redmine"]
  end

  # No zap stanza required

end
